name: aerofix-prod
services:
  db-prod:
    image: mariadb:11.3.2
    container_name: aerofix-db-prod
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - network-aerofix-prod

  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerofix-api-prod
    ports:
      - "8080:8080"
    depends_on:
      db-prod:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mariadb://db-prod:3306/aerofix_db
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - network-aerofix-prod

networks:
  network-aerofix-prod:
    driver: bridge