name: aerofix
services:
  aerofix-db:
    image: mariadb:11.3.2
    container_name: aerofix-db
    restart: always
    environment:
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - network-aerofix

  aerofix-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerofix-api
    ports:
      - "8080:8080"
    depends_on:
      aerofix-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - network-aerofix

  apiman:
    image: apiman/gateway:latest
    container_name: apiman
    ports:
      - "8081:8080"  # APIMan responderá en el puerto 8081 para no chocar con la API
      - "8444:8443"
    networks:
      - network-aerofix
    environment:
      APIMAN_GATEWAY_ENDPOINT_TYPE: rest

networks:
  network-aerofix:
    driver: bridge